# My Jupyter Notebook on IBM Watson Studio

**Temitope Lawal**

Data Analyst

_I am interested in Data Science because of how I can contribute to the world. I am particularly interested in working in the energy industry, and helping energy companies get more insights into the world consumption of energy using data science._

### Addition of 2 and 3

In [2]:
2+3

5

1. Data Scientists
2. Data Analysts
3. Data Engineers

- Tools
    * Python
    * R studio
    * Jupyter Notebook
 
| Name | Date of Birth | Country|
|------|---------------|--------|
|_Temitope_| 22/10/1989 | Nigeria|
|**Susan**| 11/08/2000 | UK|
|`Sam`| 24/06/1997 | Dubai|

> I have inserted blocked quote here.